name: Docs

on:
  push:
    paths:
      - '.github/workflows/docs.yaml'
      - 'retry.nim'
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    env:
      NIM_VERSION: stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v3
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ env.NIM_VERSION }}
    - uses: jiro4989/setup-nim-action@v1
    - run: nimble doc retry
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        tag_name: ${{ steps.prepare_tag.outputs.DEPLOY_TAG_NAME }}
        tag_message: 'Deployment ${{ github.ref_name }}'
